### ISSUE TITLE
请检查

### ISSUE THREAD

**Issue by andan179** [CarrDing/cfmmc#1]
多谢大佬分享，请检查下代码是不是有要清理的私人信息

**Comment by CarrDing** [comment]
感恩！！

**Comment by andan179** [comment]
是有账号密码，还没删除呢





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarrDing/cfmmc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月29日(星期三) 晚上9:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CarrDing/cfmmc] 请检查 (Issue #1)





 
感恩！！

**Comment by CarrDing** [comment]
谢谢大家
